#!/bin/bash

TAG="local"
NAME="ros2_humble"

CMD=" "
for (( i=2; i <= $#; i++ ))
do
  CMD+=${!i}
  CMD+=" "
done

if [[ ( $1 == "build" || $1 == "b" ) ]]; then
  docker build -t ${NAME}:${TAG} .

elif [[ ( $1 == "start" || $1 == "u" ) ]]; then
  docker run -it \
             -d \
             --rm \
             --env="DISPLAY" \
             -e "TERM=xterm-256color" \
             -v  /tmp/.X11-unix:/tmp/.X11-unix:rw \
             --name ${NAME} \
             ${CMD} \
             ${NAME}:${TAG}

elif [[ ( $1 == "stop" || $1 == "s" ) ]]; then
  docker stop -t 5 ${NAME}

elif [[ ( $1 == "connect" || $1 == "a" ) ]]; then
  docker exec -it ${NAME} bash

fi
